---
- hosts: all
  tasks:
  - name: "Scan packages (Unix/Linux)"
    scan_packages:
      os_family: '{{ ansible_os_family }}'
    when: ansible_os_family != "Windows"
    register: installed
  - name: print
    debug: var=ansible_facts.packages
